# Generated by Django 3.1.7 on 2021-03-21 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=50)),
                ('wtglocalnumber', models.CharField(max_length=3)),
                ('wtgnumber', models.CharField(max_length=15)),
                ('technician_two', models.CharField(max_length=50)),
                ('technician_three', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('activity_1', models.CharField(choices=[('Travel Office --> WTG', 'Travel Office --> WTG '), ('Travel WTG --> Office', 'Travel WTG --> Office'), ('Travel Hotel --> WTG', 'Travel Hotel --> WTG'), ('Travel WTG --> Hotel', 'Travel WTG --> Hotel'), ('Travel Extra', 'Travel Extra'), ('Work Preparation', 'Work Preparation'), ('UT Inspection', 'UT Inspection'), ('Standby Weather', 'Standby Weather'), ('Standby WTG Disorder', 'Standby WTG Disorder'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], max_length=50)),
                ('time_start_1', models.TimeField(blank=True, null=True)),
                ('time_end_1', models.TimeField(blank=True, null=True)),
                ('note_1', models.CharField(blank=True, max_length=200)),
                ('activity_2', models.CharField(choices=[('Travel Office --> WTG', 'Travel Office --> WTG '), ('Travel WTG --> Office', 'Travel WTG --> Office'), ('Travel Hotel --> WTG', 'Travel Hotel --> WTG'), ('Travel WTG --> Hotel', 'Travel WTG --> Hotel'), ('Travel Extra', 'Travel Extra'), ('Work Preparation', 'Work Preparation'), ('UT Inspection', 'UT Inspection'), ('Standby Weather', 'Standby Weather'), ('Standby WTG Disorder', 'Standby WTG Disorder'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], max_length=50)),
                ('time_start_2', models.TimeField(blank=True, null=True)),
                ('time_end_2', models.TimeField(blank=True, null=True)),
                ('note_2', models.CharField(blank=True, max_length=200)),
                ('activity_3', models.CharField(choices=[('Travel Office --> WTG', 'Travel Office --> WTG '), ('Travel WTG --> Office', 'Travel WTG --> Office'), ('Travel Hotel --> WTG', 'Travel Hotel --> WTG'), ('Travel WTG --> Hotel', 'Travel WTG --> Hotel'), ('Travel Extra', 'Travel Extra'), ('Work Preparation', 'Work Preparation'), ('UT Inspection', 'UT Inspection'), ('Standby Weather', 'Standby Weather'), ('Standby WTG Disorder', 'Standby WTG Disorder'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], max_length=50)),
                ('time_start_3', models.TimeField(blank=True, null=True)),
                ('time_end_3', models.TimeField(blank=True, null=True)),
                ('note_3', models.CharField(blank=True, max_length=200)),
                ('activity_4', models.CharField(choices=[('Travel Office --> WTG', 'Travel Office --> WTG '), ('Travel WTG --> Office', 'Travel WTG --> Office'), ('Travel Hotel --> WTG', 'Travel Hotel --> WTG'), ('Travel WTG --> Hotel', 'Travel WTG --> Hotel'), ('Travel Extra', 'Travel Extra'), ('Work Preparation', 'Work Preparation'), ('UT Inspection', 'UT Inspection'), ('Standby Weather', 'Standby Weather'), ('Standby WTG Disorder', 'Standby WTG Disorder'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], max_length=50)),
                ('time_start_4', models.TimeField(blank=True, null=True)),
                ('time_end_4', models.TimeField(blank=True, null=True)),
                ('note_4', models.CharField(blank=True, max_length=200)),
                ('activity_5', models.CharField(choices=[('Travel Office --> WTG', 'Travel Office --> WTG '), ('Travel WTG --> Office', 'Travel WTG --> Office'), ('Travel Hotel --> WTG', 'Travel Hotel --> WTG'), ('Travel WTG --> Hotel', 'Travel WTG --> Hotel'), ('Travel Extra', 'Travel Extra'), ('Work Preparation', 'Work Preparation'), ('UT Inspection', 'UT Inspection'), ('Standby Weather', 'Standby Weather'), ('Standby WTG Disorder', 'Standby WTG Disorder'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], max_length=50)),
                ('time_start_5', models.TimeField(blank=True, null=True)),
                ('time_end_5', models.TimeField(blank=True, null=True)),
                ('note_5', models.CharField(blank=True, max_length=200)),
                ('activity_6', models.CharField(choices=[('Travel Office --> WTG', 'Travel Office --> WTG '), ('Travel WTG --> Office', 'Travel WTG --> Office'), ('Travel Hotel --> WTG', 'Travel Hotel --> WTG'), ('Travel WTG --> Hotel', 'Travel WTG --> Hotel'), ('Travel Extra', 'Travel Extra'), ('Work Preparation', 'Work Preparation'), ('UT Inspection', 'UT Inspection'), ('Standby Weather', 'Standby Weather'), ('Standby WTG Disorder', 'Standby WTG Disorder'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], max_length=50)),
                ('time_start_6', models.TimeField(blank=True, null=True)),
                ('time_end_6', models.TimeField(blank=True, null=True)),
                ('note_6', models.CharField(blank=True, max_length=200)),
                ('technician_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
