# Generated by Django 3.1.7 on 2021-03-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='technician_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.technician'),
        ),
    ]
