# Generated by Django 3.1.7 on 2021-03-22 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_inspection_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('inspection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.inspection')),
            ],
        ),
    ]
