# Generated by Django 3.1.7 on 2021-04-01 12:29

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
